const PRESETS = {
  nextjs: [
    'NODE_ENV:enum(development,test,production):required:Runtime environment',
    'NEXT_PUBLIC_APP_URL:url:optional:Public application URL',
    'DATABASE_URL:url:optional:Database connection URL',
    'AUTH_SECRET:string:optional:Auth secret',
    '@require-if:NODE_ENV=production:AUTH_SECRET:AUTH_SECRET is required in production'
  ],
  vite: [
    'NODE_ENV:enum(development,test,production):required:Runtime environment',
    'VITE_APP_URL:url:optional:Public application URL',
    'VITE_API_URL:url:optional:Public API URL'
  ],
  express: [
    'NODE_ENV:enum(development,test,production):required:Runtime environment',
    'PORT:port:required:HTTP server port:default=3000',
    'DATABASE_URL:url:optional:Database connection URL',
    'SESSION_SECRET:string:optional:Session secret',
    '@require-if:NODE_ENV=production:SESSION_SECRET:SESSION_SECRET is required in production'
  ],
  prisma: [
    'DATABASE_URL:url:required:Prisma database URL',
    'DIRECT_URL:url:optional:Direct database URL'
  ],
  postgres: [
    'DATABASE_URL:url:required:Postgres connection URL',
    'PGSSLMODE:enum(disable,allow,prefer,require,verify-ca,verify-full):optional:Postgres SSL mode'
  ],
  stripe: [
    'STRIPE_SECRET_KEY:string:required:Stripe secret key',
    'STRIPE_WEBHOOK_SECRET:string:optional:Stripe webhook signing secret',
    'NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:string:optional:Stripe publishable key'
  ],
  clerk: [
    'CLERK_SECRET_KEY:string:required:Clerk secret key',
    'NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:string:required:Clerk publishable key',
    'NEXT_PUBLIC_CLERK_SIGN_IN_URL:string:optional:Clerk sign-in path',
    'NEXT_PUBLIC_CLERK_SIGN_UP_URL:string:optional:Clerk sign-up path'
  ],
  authjs: [
    'AUTH_SECRET:string:required:Auth.js secret',
    'AUTH_URL:url:optional:Auth.js canonical URL',
    'AUTH_TRUST_HOST:boolean:optional:Trust host header'
  ],
  sentry: [
    'SENTRY_DSN:url:optional:Sentry DSN',
    'SENTRY_AUTH_TOKEN:string:optional:Sentry auth token',
    'SENTRY_ORG:string:optional:Sentry organization slug',
    'SENTRY_PROJECT:string:optional:Sentry project slug'
  ]
};

function presetNames() {
  return Object.keys(PRESETS);
}

function schemaFromPreset(name) {
  if (!Object.prototype.hasOwnProperty.call(PRESETS, name)) {
    return null;
  }

  const lines = PRESETS[name];

  return [
    '# .env.schema',
    `# Generated by envguard init --preset ${name}`,
    '# Review every key before using this in production.',
    '',
    ...lines,
    ''
  ].join('\n');
}

module.exports = {
  presetNames,
  schemaFromPreset
};
